# STANDARD
## GENERAL
backend: 'webengine'
auto_save.session: True
confirm_quit: ['downloads']

## ALIASES
aliases: {
    # default aliases:
    "w": "session-save", "q": "close", "qa": "quit", "wq": "quit --save", "wqa": "quit --save",

    # rbuku aliases:
    "b": "spawn --userscript qb-rbuku -s",
    "ba": "spawn --userscript qb-rbuku -a",
    "br": "spawn --userscript qb-rbuku -r",

    # rofi+youtube-dl aliases:
    "rytd": "spawn --userscript qb-rytd",
    "rytda": "spawn --userscript qb-rytda"
}

## CONTENT
content.autoplay: False
content.dns_prefetch: False
content.headers.do_not_track: True
content.webgl: True

## DOWNLOADS
downloads.position: 'bottom'
downloads.remove_finished: 5000

## HINTING
hints.chars: 'asdfghjklqwertyuiopzcvbnm'
hints.find_implementation: 'python'

## TABS
tabs.last_close: 'close'
tabs.position: 'bottom'
tabs.show: 'multiple'
tabs.title.format: '[{index}] {current_title}'
tabs.title.format_pinned: '[{index}]'

## URL
url.searchengines: {
    # General
    'DEFAULT': 'https://duckduckgo.com/?q={}',
    'ddg': 'https://duckduckgo.com/?q={}',
    'sw': 'https://swisscows.com/web?query={}',
    'sa': 'https://seekingalpha.com/search/?q={}',
    'wolf': 'https://www.wolframalpha.com/input/?i={}',
    'wiki': 'https://en.wikipedia.org/?search={}',
    'dict': 'https://www.merriam-webster.com/dictionary/{}',

    # Social
    'yt': 'https://www.youtube.com/results?search_query={}',
    'sex': 'https://stackexchange.com/search?q={}',
    'ghub': 'https://github.com/search?q={}',
    'glab': 'https://gitlab.com/search?search={}',

    # Commerce
    'ex': 'https://examine.com/search/?q={}',
    'nc': 'https://www.namecheap.com/domains/registration/results.aspx?domain={}',

    # Commerce
    'ebay': 'https://www.ebay.com/sch/?_nkw={}',
    'az': 'https://www.amazon.com/s?k={}',

    # Linux
    'man': 'https://www.die.net/search/?q={}&sa=Search',

    # Arch Linux
    'arch': 'https://wiki.archlinux.org/?search={}',
    'pac': 'https://www.archlinux.org/packages/?q={}',
    'aur': 'https://aur.archlinux.org/packages/?O=0&K={}',

    # Alpine Linux
    'apk': 'https://pkgs.alpinelinux.org/packages?name={}&branch=edge&arch=armhf',

    # Void Linux
    'void': 'https://wiki.voidlinux.org/?search={}',

    # Python Docs
    'py3': 'https://docs.python.org/3/search.html?q={}',
    'conda': 'https://anaconda.org/search?q={}',
    'pip': 'https://pypi.org/search/?q={}',
    'pd': 'https://pandas.pydata.org/pandas-docs/stable/search.html?q={}',
    'np': 'https://docs.scipy.org/doc/numpy/search.html?q={}',
    'skl': 'https://scikit-learn.org/stable/search.html?q={}',
    'tch': 'https://pytorch.org/docs/stable/search.html?q={}',

    # Rust Docs
    'rbook': 'https://doc.rust-lang.org/book/title-page.html?search={}',
    'rust': 'https://doc.rust-lang.org/reference/index.html?search={}',
    'rstd': 'https://doc.rust-lang.org/std/?search={}',
    'cargo': 'https://crates.io/search?q={}'
}

## WINDOW
window.hide_decoration: True

## ZOOM
zoom.default: '150%'

# CUSTOM
## KEYBINDS
custom.keybinds: {
    'D': 'tab-close -o',
    'H': 'tab-prev',
    'J': 'back',
    'K': 'forward',
    'L': 'tab-next',
    'd': 'tab-close'
}

## Base16 Scheme - can be .Xresources or a base16 yaml file
custom.base16.file: '/home/kev/.local/share/themes/base16/base16-gruvbox-scheme/gruvbox-dark-soft.yaml'
